### ISSUE TITLE
redshift appears to stop working after resume from suspend

### ISSUE THREAD

**Issue by gordon-morehouse** [jonls/redshift#217]
Linux Mint Xfce 17.1, 32-bit, on a Core 2 Duo iMac.

redshift stops adjusting the color of the screen eventually. I believe this occurs after resume from suspend. redshift and gtk-redshift 1.9.1.1-trusty.

**Comment by maandree** [comment]
Are you talking about suspend–resume on the computer? And what about hibernate?
Suspend–resume (both SIGTSTP and SIGSTOP) on the process works as expected on version 1.10.

**Comment by maandree** [comment]
I can now comfirm this bug.

**Comment by xwhatsit** [comment]
Seeing the same thing after suspending overnight. Archlinux using the supplied systemd units to run it automatically as a user service. Method is randr (Intel Sandy Bridge graphics). Attaching strace shows repeated nanosleep calls, and when you stop the process with systemd, it waits around for a bit doing its usual ramp back to 6500K, but the screen still stays at 3500K. When I run it again manually, it instantly snaps to 6500K before ramping down to 5500K. I assume this means it's still running correctly in the background, but perhaps randr has stopped listening?

**Comment by maandree** [comment]
I think this bug can be fixed by reconnecting to the display when SIGCONT is received.

**Comment by caseydentinger** [comment]
Experiencing this in Stretch with Redshift 1.10, here's a possible workaround:

*/lib/systemd/system/redshift-resume.service*

    [Unit]
    Description=restart redshift because of a bug
    After=suspend.target

    [Service]
    User=casey
    Type=oneshot
    ExecStart=/usr/local/bin/redshift-resume
    TimeoutSec=0
    StandardOutput=syslog

    [Install]
    WantedBy=suspend.target

*/usr/local/bin/redshift-resume*

    if ! pidof -s redshift > /dev/null; then
            redshift -m randr -l 40:-105 &
    fi

**Comment by jmgrosen** [comment]
I'm having a similar bug, except restarting redshift doesn't help. Even trying to re-set the gamma using `xrandr` manually doesn't work. Has anyone else seen this / know of a fix?

**Comment by MoonSweep** [comment]
Bug confirmed on Debian Stretch, Redshift 1.11. I put the computer to sleep through an at job to run pm-suspend as root. The computer slept only for approximately 6 hours.

I still use sysvinit (but I don't think it makes a difference over systemd).

**Comment by m1cm1c** [comment]
Has this a prospect of getting fixed? Has it already been fixed by someone, just not sent upstream?

**Comment by grant-park** [comment]
still facing issue, with latest release

**Comment by shazow** [comment]
If anyone is using a redshift user-level systemd service, here's a somewhat simpler resume service I'm using:

In `~/.config/systemd/user/redshift-resume.service`:

```
[Unit]
Description=Restart redshift on resume
After=suspend.target

[Service]
ExecStart=/usr/bin/systemctl --user restart redshift.service

[Install]
WantedBy=suspend.target
```

Then run:

```console
$ systemctl --user enable redshift-resume
```

**Comment by m1cm1c** [comment]
I'm not experiencing the problem anymore ever since I started explicitly stating my coordinates. So maybe give this a shot.

**Comment by wolftune** [comment]
I'm having this trouble on KDE Neon (based on Ubuntu 20.04), at least with external monitors. I don't recall the problem with my laptop monitor itself in the past. Maybe that's a hunt. I explicitly stated my coordinates but that didn't solve the issue.

If I toggle redshift off and on, it then engages.

**Comment by gustavklopp** [comment]
Any workaround or way of debugging this? This problem started for me a few weeks ago (I don't recall exactly when).

**Comment by hlascelles** [comment]
Still a bug on Mint Linux 22. Explicitly stating coordinates does not help.

Toggling Redshift after resume makes it work. So does just changing the "temperature" by one notch.
